### ISSUE TITLE
RFE - Add additional disk installation options

### ISSUE THREAD

**Issue by paulchapmanibm** [vagfed/sno-ppc-install#2]
Great work, Federico.
I have been installing SNO manually (with a few scripts), as this means that I can install in any environment.
I would like you to consider an enhancement to enable installation to /dev/sda or another chosen disk.

Best Regards,
Paul

**Comment by vagfed** [comment]
Hi Paul. 
You must choose the installation disk by providing "bootdiskwwn" value in vars/ocp.yml. Since most installations will use SAN disks, it will be more reliable than using /dev/sda or any other label since you are never sure which disk is which. The "bootdiskwwn" is used to select /dev/disk/by-id/wwn-0x<bootdiskwwn> disk for installation which will be linked to proper /dev/sdX device at boot time (and multipath device once you enable it).
Dedicated internal disks or virtual SCSI disks may not be properly managed. I have not tested them. If you are in one of this cases can you please provide "ls -l /dev/disk/by-id"?
I can add reference to /dev/sdX disk but I wonder how you can choose the right disk before OCP is installed.

**Comment by vagfed** [comment]
Primary focus is on SAN boot with variable "bootdiskwwn" value in vars/ocp.yml. 
If you comment out the variable, the script will default in installing OCP on /dev/sda. Create a LPAR with only one disk (it may end up in having multiple paths  meaning sdb and so on) and installation will proceed. You can add other disks after installation.
